[package]
name = "rfsm"
version = "0.1.0"
edition = "2021"

[features]
default = ["ECMAScript", "EnvLog"]
ECMAScript = ["boa_engine"]
EnvLog = ["env_logger"]

[dependencies]
quick-xml = { version = "0.27.1", features = ["serialize"] }
boa_engine = { version = "0.16.0", optional = true }
log = "0.4.0"
env_logger = { version = "0.9.0", optional = true }
reqwest = { version = "0.11", features = ["blocking", "json"] }

[profile.dev.package."*"]
opt-level = "z"