//! Implementation of "executable content" elements
//! See [W3C:Executable Content](https://www.w3.org/TR/scxml/#executable)

#[cfg(test)]
use std::{println as info, println as warn};
use std::collections::HashMap;
use std::fmt;
use std::fmt::{Debug, Display, Formatter};

use lazy_static::lazy_static;
#[cfg(not(test))]
use log::{info, warn};
use log::error;
use regex::Regex;

use crate::{Event, EventType, get_global};
use crate::datamodel::{Datamodel, SCXML_EVENT_PROCESSOR, ToAny};
use crate::fsm::{Cancel, ExecutableContentId, Fsm, Parameter, SendParameters, vec_to_string};

pub const TARGET_INTERNAL: &str = "_internal";
pub const TARGET_SCXML_EVENT_PROCESSOR: &str = "http://www.w3.org/TR/scxml/#SCXMLEventProcessor";

pub const TYPE_IF: &str = "if";
pub const TYPE_EXPRESSION: &str = "expression";
pub const TYPE_SCRIPT: &str = "script";
pub const TYPE_LOG: &str = "log";
pub const TYPE_FOREACH: &str = "foreach";
pub const TYPE_SEND: &str = "send";
pub const TYPE_RAISE: &str = "raise";
pub const TYPE_CANCEL: &str = "cancel";
pub const TYPE_ASSIGN: &str = "assign";

pub trait ExecutableContent: ToAny + Debug + Send {
    fn execute(&self, datamodel: &mut dyn Datamodel, fsm: &Fsm);
    fn get_type(&self) -> &str;
    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, fsm: &Fsm);
}

pub fn get_safe_executable_content_as<T: 'static>(ec: &mut dyn ExecutableContent) -> &mut T {
    let va = ec.as_any();
    match va.downcast_mut::<T>() {
        Some(v) => {
            v
        }
        None => {
            panic!("Failed to cast executable content")
        }
    }
}


pub fn get_executable_content_as<T: 'static>(ec: &mut dyn ExecutableContent) -> Option<&mut T> {
    let va = ec.as_any();
    match va.downcast_mut::<T>() {
        Some(v) => {
            Some(v)
        }
        None => {
            None
        }
    }
}


pub fn get_opt_executable_content_as<T: 'static>(ec_opt: Option<&mut dyn ExecutableContent>) -> Option<&mut T> {
    match ec_opt {
        Some(ec) => {
            get_executable_content_as::<T>(ec)
        }
        None => { None }
    }
}


pub trait ExecutableContentTracer {
    fn print_name_and_attributes(&mut self, ec: &dyn ExecutableContent, attrs: &[(&str, &String)]);
    fn print_sub_content(&mut self, name: &str, fsm: &Fsm, content: ExecutableContentId);
}


#[derive(Debug)]
pub struct Script {
    pub content: Vec<ExecutableContentId>,
}

#[derive(Debug)]
pub struct Expression {
    pub content: String,
}

#[derive(Debug)]
pub struct Log {
    pub label: String,
    pub expression: String,
}

#[derive(Debug)]
pub struct If {
    pub condition: String,
    pub content: ExecutableContentId,
    pub else_content: ExecutableContentId,

}

#[derive(Debug)]
pub struct ForEach {
    pub array: String,
    pub item: String,
    pub index: String,
    pub content: ExecutableContentId,
}


/// #W3C says:
/// The \<raise\> element raises an event in the current SCXML session.\
/// Note that the event will not be processed until the current block of executable content has completed
/// and all events that are already in the internal event queue have been processed. For example, suppose
/// the \<raise\> element occurs first in the \<onentry\> handler of state S followed by executable content
/// elements ec1 and ec2. If event e1 is already in the internal event queue when S is entered, the event
/// generated by \<raise\> will not be processed until ec1 and ec2 have finished execution and e1 has been
/// processed.
///
pub struct Raise {
    pub event: String,
}

pub struct Assign {
    pub location: String,
    pub expr: String,
}

impl Assign {
    pub fn new() -> Assign {
        Assign {
            location: String::new(),
            expr: String::new(),
        }
    }
}

impl Debug for Assign {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Assign")
            .field("location", &self.location)
            .field("expr", &self.expr)
            .finish()
    }
}

impl ExecutableContent for Assign {
    fn execute(&self, datamodel: &mut dyn Datamodel, fsm: &Fsm) {
        datamodel.assign(fsm, &self.location.as_str(), &self.expr);
    }

    fn get_type(&self) -> &str {
        TYPE_ASSIGN
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, _fsm: &Fsm) {
        tracer.print_name_and_attributes(self, &[("location", &self.location), ("expr", &self.expr)]);
    }
}


impl Raise {
    pub fn new() -> Raise {
        Raise {
            event: String::new(),
        }
    }
}

impl Debug for Raise {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Raise")
            .field("event", &self.event)
            .finish()
    }
}

impl ExecutableContent for Raise {
    fn execute(&self, datamodel: &mut dyn Datamodel, _fsm: &Fsm) {
        let event = Event::new("", &self.event, &None);
        get_global!(datamodel).internalQueue.enqueue(event);
    }

    fn get_type(&self) -> &str {
        TYPE_RAISE
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, _fsm: &Fsm) {
        tracer.print_name_and_attributes(self, &[("event", &self.event)]);
    }
}

impl Script {
    pub fn new() -> Script {
        Script {
            content: Vec::new(),
        }
    }
}

impl ExecutableContent for Script {
    fn execute(&self, datamodel: &mut dyn Datamodel, fsm: &Fsm) {
        for s in &self.content {
            let _l = datamodel.executeContent(fsm, *s);
        }
    }

    fn get_type(&self) -> &str {
        TYPE_SCRIPT
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, _fsm: &Fsm) {
        // TODO: Shall we print any sub-content?
        tracer.print_name_and_attributes(self, &[("content", &vec_to_string(&self.content))]);
    }
}

impl Expression {
    pub fn new() -> Expression {
        Expression {
            content: String::new(),
        }
    }
}

impl ExecutableContent for Expression {
    fn execute(&self, datamodel: &mut dyn Datamodel, fsm: &Fsm) {
        let _l = datamodel.execute(fsm, &self.content);
    }

    fn get_type(&self) -> &str {
        TYPE_EXPRESSION
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, _fsm: &Fsm) {
        tracer.print_name_and_attributes(self, &[("content", &self.content)]);
    }
}

impl Log {
    pub fn new(label: &Option<&String>, expression: &str) -> Log {
        Log {
            label: label.unwrap_or(&"".to_string()).clone(),
            expression: expression.to_string(),
        }
    }
}

impl ExecutableContent for Log {
    fn execute(&self, datamodel: &mut dyn Datamodel, fsm: &Fsm) {
        let l = datamodel.execute(fsm, &self.expression);
        if l.is_some() {
            datamodel.log(&l.unwrap());
        }
    }

    fn get_type(&self) -> &str {
        TYPE_LOG
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, _fsm: &Fsm) {
        tracer.print_name_and_attributes(self, &[
            ("expression", &self.expression)]);
    }
}

impl If {
    pub fn new(condition: &String) -> If {
        If {
            condition: condition.clone(),
            content: 0,
            else_content: 0,
        }
    }
}

impl ExecutableContent for If {
    fn execute(&self, datamodel: &mut dyn Datamodel, fsm: &Fsm) {
        match datamodel.execute_condition(fsm, &self.condition) {
            Ok(r) => {
                if r {
                    if self.content != 0 {
                        for e in fsm.executableContent.get(&self.content).unwrap() {
                            e.execute(datamodel, fsm);
                        }
                    }
                } else {
                    if self.else_content != 0 {
                        for e in fsm.executableContent.get(&self.else_content).unwrap() {
                            e.execute(datamodel, fsm);
                        }
                    }
                }
            }
            Err(e) => {
                warn!("Condition {} can't be evaluated. {}", self.condition, e);
            }
        }
    }

    fn get_type(&self) -> &str {
        TYPE_IF
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, fsm: &Fsm) {
        tracer.print_name_and_attributes(self, &[
            ("condition", &self.condition)
        ]);
        tracer.print_sub_content("then", fsm, self.content);
        tracer.print_sub_content("else", fsm, self.else_content);
    }
}

pub const INDEX_TEMP: &str = "__$index";

impl ForEach {
    pub fn new() -> ForEach {
        ForEach {
            array: "".to_string(),
            item: "".to_string(),
            index: "".to_string(),
            content: 0,
        }
    }
}

impl ExecutableContent for ForEach {
    fn execute(&self, datamodel: &mut dyn Datamodel, fsm: &Fsm) {
        let idx = if self.index.is_empty()
        {
            INDEX_TEMP.to_string()
        } else {
            self.index.clone()
        };
        datamodel.execute_for_each(fsm, &self.array, &self.item, &idx, &mut |datamodel| {
            if self.content != 0 {
                for e in fsm.executableContent.get(&self.content).unwrap() {
                    e.execute(datamodel, fsm);
                }
            }
        });
    }

    fn get_type(&self) -> &str {
        TYPE_FOREACH
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, fsm: &Fsm) {
        tracer.print_name_and_attributes(self, &[
            ("array", &self.array),
            ("item", &self.item),
            ("index", &self.index)]);
        tracer.print_sub_content("content", fsm, self.content);
    }
}

impl Parameter {
    pub fn new() -> Parameter {
        Parameter {
            name: "".to_string(),
            expr: "".to_string(),
            location: "".to_string(),
        }
    }
}

impl Display for Parameter {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "Parameter{{name:{} expr:{} location:{}}}", self.name, self.expr, self.location)
    }
}

impl ExecutableContent for Cancel {
    fn execute(&self, _datamodel: &mut dyn Datamodel, _fsm: &Fsm) {
        todo!()
    }

    fn get_type(&self) -> &str {
        TYPE_CANCEL
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, _fsm: &Fsm) {
        tracer.print_name_and_attributes(self,
                                         &[
                                             ("sendid", &self.send_id),
                                             ("sendidexpr", &self.send_id_expr)
                                         ]);
    }
}

/// Implements the execution of \<send\> element.
impl ExecutableContent for SendParameters {
    /// If unable to dispatch, place "error.communication" in internal queue
    /// If target is not supported, place "error.execution" in internal queue
    fn execute(&self, datamodel: &mut dyn Datamodel, fsm: &Fsm) {
        let target =
            if self.target.is_empty()
            {
                if !self.target_expr.is_empty() {
                    match datamodel.execute(fsm, &self.target_expr) {
                        None => {
                            // Error -> abort
                            return;
                        }
                        Some(value) => {
                            value
                        }
                    }
                } else {
                    // TODO: Clarify. Missing target -> abort or ignore?
                    datamodel.internal_error_execution();
                    return;
                }
            } else {
                self.target.clone()
            };

        let event_name =
            if self.event.is_empty()
            {
                if !self.event_expr.is_empty() {
                    match datamodel.execute(fsm, &self.event_expr) {
                        None => {
                            // Error -> abort
                            return;
                        }
                        Some(name) => {
                            name
                        }
                    }
                } else {
                    "".to_string()
                }
            } else {
                self.event.clone()
            };

        let send_id =
            if self.name_location.is_empty() {
                self.name.clone()
            } else {
                match datamodel.get_by_location(self.name_location.as_str()) {
                    None => {
                        // Error -> abort
                        return;
                    }
                    Some(id) => {
                        id.value.unwrap()
                    }
                }
            };

        let mut data_map = HashMap::new();

        for param in &self.params {
            if !param.expr.is_empty() {
                match datamodel.execute(fsm, &param.expr) {
                    None => {
                        //  W3C:\
                        // ...if the evaluation of the 'expr' produces an error, the SCXML
                        // Processor must place the error 'error.execution' on the internal event
                        // queue and must ignore the name and value.
                        error!("Send: expr of param {} is invalid - ignored", param);
                    }
                    Some(value) => {
                        data_map.insert(param.name.clone(), value);
                    }
                }
            } else if !param.location.is_empty() {
                match datamodel.get_by_location(&param.location.as_str()) {
                    None => {
                        //  W3C:\
                        // If the 'location' attribute does not refer to a valid location in
                        // the data model, ..., the SCXML Processor must place the error
                        // 'error.execution' on the internal event queue and must ignore the name
                        // and value.
                        error!("Send: location of param {} is invalid - ignored", param);
                    }
                    Some(data) => {
                        data_map.insert(param.name.clone(), data.value.unwrap());
                    }
                }
            }
        }

        let delay_ms =
            if !self.delay_expr.is_empty() {
                match datamodel.execute(fsm, &self.delay_expr) {
                    None => {
                        // Error -> Abort
                        return;
                    }
                    Some(delay) => {
                        parse_duration_to_milliseconds(&delay)
                    }
                }
            } else {
                self.delay_ms as i64
            };

        if delay_ms < 0
        {
            // Delay is invalid -> Abort
            error!("Send: delay {} is negative", self.delay_expr);
            datamodel.internal_error_execution();
            return;
        }

        if delay_ms > 0 && target.eq(TARGET_INTERNAL) {
            // Can't send via internal queue
            error!("Send: illegal delay for target {}", target);
            datamodel.internal_error_execution();
        } else {
            let location =
                datamodel.get_io_processors().get_mut(SCXML_EVENT_PROCESSOR).map_or(
                    "".to_string(),
                    |io_processor| io_processor.get_location().to_string());

            let sender = get_global!(datamodel).externalQueue.sender.clone();

            fsm.schedule(delay_ms, move || {
                // @TODO: fill all fields correctly!
                let event = Box::new(Event {
                    name: event_name.clone(),
                    etype: EventType::external,
                    sendid: send_id.clone(),
                    origin: location.clone(),
                    origin_type: "".to_string(),
                    invoke_id: 0,
                    data: data_map.clone(),
                });
                let _ignored = sender.send(event);
            });
        }
    }


    fn get_type(&self) -> &str {
        TYPE_SEND
    }

    fn trace(&self, tracer: &mut dyn ExecutableContentTracer, _fsm: &Fsm) {
        tracer.print_name_and_attributes(self, &[
            ("name_location", &self.name_location),
            ("name", &self.name),
            ("name", &self.name),
            ("event_expr", &self.event_expr),
            ("target", &self.target),
            ("target_expr", &self.target_expr),
            ("type", &self.type_value),
            ("type_expr", &self.type_expr),
            ("delay", &self.delay_ms.to_string()),
            ("delay_expr", &self.delay_expr),
            ("name_list", &self.name_list),
            ("content", &self.content),
            ("params", &vec_to_string(&self.params))
        ]);
    }
}


#[cfg(test)]
mod tests {
    use crate::executable_content::parse_duration_to_milliseconds;

    #[test]
    fn delay_parse() {
        assert_eq!(parse_duration_to_milliseconds(&"6.7s".to_string()), 6700);
        assert_eq!(parse_duration_to_milliseconds(&"0.5d".to_string()), 12 * 60 * 60 * 1000);
        assert_eq!(parse_duration_to_milliseconds(&"1m".to_string()), 60 * 1000);
        assert_eq!(parse_duration_to_milliseconds(&"0.001s".to_string()), 1);
        assert_eq!(parse_duration_to_milliseconds(&"6.7S".to_string()), 6700);
        assert_eq!(parse_duration_to_milliseconds(&"0.5D".to_string()), 12 * 60 * 60 * 1000);
        assert_eq!(parse_duration_to_milliseconds(&"1M".to_string()), 60 * 1000);
        assert_eq!(parse_duration_to_milliseconds(&"0.001S".to_string()), 1);

        assert_eq!(parse_duration_to_milliseconds(&"x1S".to_string()), -1);
        assert_eq!(parse_duration_to_milliseconds(&"1Sx".to_string()), -1);
    }
}


/// a duration.
/// RegExp: "\\d*(\\.\\d+)?(ms|s|m|h|d))").
pub fn parse_duration_to_milliseconds(d: &String) -> i64 {
    lazy_static! {
        static ref DURATION_RE: Regex = Regex::new(r"^(\d*(\.\d+)?)(MS|S|M|H|D|ms|s|m|h|d)$").unwrap();
    }
    if d.is_empty() {
        0
    } else {
        let caps = DURATION_RE.captures(d);
        if caps.is_none() {
            -1
        } else {
            let cap = caps.unwrap();
            let value = cap.get(1).map_or("", |m| m.as_str());
            let unit = cap.get(3).map_or("", |m| m.as_str());

            if value.is_empty() {
                0
            } else {
                let mut v: f64 = value.parse::<f64>().unwrap();
                match unit {
                    "D" | "d" => {
                        v = v * 24.0 * 60.0 * 60.0 * 1000.0;
                    }
                    "H" | "h" => {
                        v = v * 60.0 * 60.0 * 1000.0;
                    }
                    "M" | "m" => {
                        v = v * 60000.0;
                    }
                    "S" | "s" => {
                        v = v * 1000.0;
                    }
                    "MS" | "ms" => {}
                    _ => {
                        return -1;
                    }
                }
                v.round() as i64
            }
        }
    }
}

pub struct DefaultExecutableContentTracer {
    trace_depth: usize,

}

impl DefaultExecutableContentTracer {
    pub fn new() -> DefaultExecutableContentTracer {
        DefaultExecutableContentTracer {
            trace_depth: 0,
        }
    }

    pub fn trace(&self, msg: &str)
    {
        info!("{:1$}{2}"," ", 2 * self.trace_depth, msg);
    }
}

impl ExecutableContentTracer for DefaultExecutableContentTracer {
    fn print_name_and_attributes(&mut self, ec: &dyn ExecutableContent, attrs: &[(&str, &String)]) {
        let mut buf = String::new();

        buf.push_str(format!("{:1$}{2} [", " ", 2 * self.trace_depth, ec.get_type()).as_str());

        let mut first = true;
        for (name, value) in attrs {
            if !value.is_empty() {
                if first {
                    first = false;
                } else {
                    buf.push(',');
                }
                buf.push_str(format!("{}:{}", name, value).as_str());
            }
        }
        buf.push_str("]");

        self.trace(&buf);
    }

    fn print_sub_content(&mut self, name: &str, fsm: &Fsm, content_id: ExecutableContentId) {
        self.trace(format!("{:1$}{2} {{", " ", 2 * self.trace_depth, name).as_str());
        self.trace_depth += 1;
        match fsm.executableContent.get(&content_id) {
            Some(vec) => {
                for ec in vec {
                    ec.trace(self, fsm);
                }
            }
            None => {}
        }
        self.trace_depth -= 1;
        self.trace(format!("{:1$}}}", " ", 2 * self.trace_depth).as_str());
    }
}
